// Seeder. Idempotent, re-runnable, <1s on the memory store.
//
// Staged documents are deliberately NOT loaded here. They arrive one at a time during
// the demo via POST /api/clients/:id/documents — that arrival is the whole show.

import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createStore } from "../src/store.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA = join(HERE, "..", "data", "demo-data.json");

export async function loadDemoData() {
  return JSON.parse(await readFile(DATA, "utf8"));
}

export async function seed(store) {
  const demo = await loadDemoData();

  const client = {
    _id: demo.persona._id,
    name: demo.persona.name,
    country: demo.persona.country,
    status: demo.persona.status ?? "ONBOARDING",
    entity: demo.persona.entity,
    required_fields: demo.persona.required_fields,
    resolved_fields: { ...(demo.persona.resolved_fields ?? {}) },
  };

  await store.load({
    clients: [client],
    documents: [],
    verdicts: demo.verdicts ?? [],
    entities: demo.entities ?? [],
    ownership: demo.ownership ?? [],
    cases: [],
    score_events: [],
  });

  return {
    client: client._id,
    verdicts: (demo.verdicts ?? []).length,
    entities: (demo.entities ?? []).length,
    ownership: (demo.ownership ?? []).length,
    staged: (demo.staged_documents ?? []).length,
  };
}

// CLI
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const store = await createStore();
  const counts = await seed(store);
  console.log("[seed]", counts);

  if (store.mode === "mongo") {
    console.log(
      "\n[seed] Reminder: automated embedding is generated by Atlas, not by this script.\n" +
        "       Create the vector index on verdicts.rationale and wait for it to reach\n" +
        "       status READY before scoring, or precedent retrieval returns nothing.\n" +
        "       See atlas/indexes.md."
    );
  }
  await store.close();
}
